spring:
#  thymeleaf:
#    encoding: UTF-8
#    content-type: text/html
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/static/

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://120.79.175.210:3306/apple?useSSL=true&useUnicode=true&characterEncoding=utf-8
#      username: prod
#      password: jkdfjalksdjflaJLJFJljjdfa!@@#hdfjh%$#^&j3241324
      url: jdbc:mysql://127.0.0.1:3306/apple?useSSL=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: password
      filter:
        stat:
          log-slow-sql: true


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.nplat.convert.entity
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    capital-mode: true
    id-type: 0
  configuration:
    map-underscore-to-camel-case: true



ali-oos:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIY3UyR56UqQ5J
  accessKeySecret: 3Qlfz3TjdvMQnvOP1lOwkzR3Hp15mj
  bucket_1: wx-upload-file
  enterpriseFolder: enterprise

weChat:
  appId: wxe1a48f73244684be
  secret: f7ee23b40c112fd2a296ecc95b0589a5