spring:
  thymeleaf:
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/static/
server:
  port: 8080

ali-oos:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIY3UyR56UqQ5J
  accessKeySecret: 3Qlfz3TjdvMQnvOP1lOwkzR3Hp15mj
  bucket_1: wx-upload-file
